# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ea5a37d9f0bff410fc7b5616203ff0db83eb7f8fefbd073e3eb595dffc24d28b13bb3343727f84a23c76146c3c2af51c548257bd22cce18e92c3227fddcad818

test:
  secret_key_base: e19d643258fb3441568864372a8f97d08aa81ddbde0ebe9bd288b53bc4bb5db4e961fdfd1da4b0de1d134203bab742c6053531a10ddaa6ebf3b21847e29a6960

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
